// Scaffolding generated by Claude
import { MongoMemoryServer } from 'mongodb-memory-server';
import mongoose from 'mongoose';

let mongod: MongoMemoryServer;

export async function connectTestDB() {
    try{
        mongod = await MongoMemoryServer.create();
        const uri = mongod.getUri();
        await mongoose.connect(uri);
        console.log("Successfully connected to test db!")
    }catch (error){
        console.log("Error connecting to the test db!")
    }

}

export async function closeTestDB() {
    await mongoose.connection.dropDatabase();
    await mongoose.connection.close();
    await mongod.stop();
}

export async function clearTestDB() {
    const collections = mongoose.connection.collections;
    for (const key in collections) {
        if(!collections[key]) continue;
        await collections[key].deleteMany({});
    }
}