// Scaffolding generated by Claude
import {createApi} from "@reduxjs/toolkit/query/react";
import {apiBaseQuery} from "./apiBaseQuery";

export const api = createApi({
    reducerPath: "api",
    baseQuery: apiBaseQuery,
    tagTypes: ["Booking", "MachineStatus", "Room", "Credits",
        "Transactions", "ReservationSlots",
        "MaintenanceRequests", "Notices", "User", "Residents", "CurrentUser", "IoTServices", "IoTStatus"],
    endpoints: () => ({}),
});