// Scaffolding generated by Claude.
import type {BaseQueryFn} from "@reduxjs/toolkit/query";
import {fetchBaseQuery} from "@reduxjs/toolkit/query/react";

const BASE_URL = import.meta.env.VITE_API_BASE ?? "http://localhost:3000";

type ApiError = { status: number; message: string };

const rawBaseQuery = fetchBaseQuery({
    baseUrl: BASE_URL,
    credentials: "include",
});

export const apiBaseQuery: BaseQueryFn<{ url: string; method?: string; body?: unknown }, unknown, ApiError> =
    async (args, api, extraOptions) => {
    const result = await rawBaseQuery(args, api, extraOptions);

    if (result.error) {
        const data = result.error.data as { message?: string } | undefined;
        return {
            error: {
                status: Number(result.error.status),
                message: data?.message ?? `HTTP error ${result.error.status}`
            }
        };
    }

    const payload = result.data;
    if (payload && typeof payload === "object" && "success" in (payload as object)) {
        const envelope = payload as { success: boolean; message?: string; data?: unknown };
        if (!envelope.success) {
            return {error: {status: 200, message: envelope.message ?? "API request failed"}};
        }
        return {data: envelope.data};
    }

    return {data: payload};
};