// Scaffolding generated by Claude.
import type {
    BaseQueryApi,
    BaseQueryFn, FetchArgs,
    FetchBaseQueryError,
    FetchBaseQueryMeta,
    QueryReturnValue
} from "@reduxjs/toolkit/query";
import {fetchBaseQuery} from "@reduxjs/toolkit/query/react";
import {logOut} from "@/context/authenticationSlice.ts";

const BASE_URL = import.meta.env.VITE_API_BASE ?? "http://localhost:3000";

type ApiError = { status: number; message: string };

const rawBaseQuery = fetchBaseQuery({
    baseUrl: BASE_URL,
    credentials: "include",
});

// Holds the single in-flight refresh call, if one is happening.
// null means no refresh currently in progress.
let refreshPromise: ReturnType<typeof rawBaseQuery> | null = null;

//Handles 401 response
const handleUnauthorized = async (
    result: QueryReturnValue<unknown, FetchBaseQueryError, FetchBaseQueryMeta>,
    api: BaseQueryApi,
    args: FetchArgs,
    extraOptions: object) => {
    if (result.error?.status !== 401) return result;

    // If nobody's refreshing yet, kick one off and store the promise.
    // If someone already is, just reuse their promise.
    if (!refreshPromise) {
        refreshPromise = rawBaseQuery(
            {url: "/refresh", method: "POST"},
            api,
            extraOptions
        );
    }

    const refreshResult = await refreshPromise;

    // Whoever finishes awaiting first clears it so the *next* 401
    // (a future, separate expiry) can trigger a new refresh.
    refreshPromise = null;

    if (!refreshResult.data) {
        api.dispatch(logOut());
        return result;
    }
    return rawBaseQuery(args, api, extraOptions);

}

export const apiBaseQuery: BaseQueryFn<{ url: string; method?: string; body?: unknown }, unknown, ApiError> =
    async (args, api, extraOptions) => {

        let result = await rawBaseQuery(args, api, extraOptions);
        result = await handleUnauthorized(result, api, args, extraOptions);

        if (result.error) {
            const data = result.error.data as { message?: string } | undefined;
            return {
                error: {
                    status: Number(result.error.status),
                    message: data?.message ?? `HTTP error ${result.error.status}`
                }
            };
        }

        const payload = result.data;
        if (payload && typeof payload === "object" && "success" in (payload as object)) {
            const envelope = payload as { success: boolean; message?: string; data?: unknown };
            if (!envelope.success) {
                return {error: {status: 200, message: envelope.message ?? "API request failed"}};
            }
            return {data: envelope.data};
        }

        return {data: payload};
    };