// Scaffolding generated by Claude
import { api } from "../api";
import type {Role} from "@/dataTypes/user.ts";
import {logIn} from "@/context/authenticationSlice.ts";

export interface RefreshResponse {
    message: string;
    type: string;
    data: AuthUser;
}

export interface SignUpRequest {
    name: string | null,
    email: string | null;
    password: string | null;
    phoneNumber: string | null,
    roles: Role[],
}

export interface AuthResponse {
    message: string;
    data: AuthUser;
    type: string;
}

export interface LoginRequest {
    username?: string;
    email?: string;
    password: string;
}

export interface AuthUser {
    _id: string;
    name: string;
    phoneNumber: string;
    username: string;
    email: string;
    roles: string[];
}

export const authApi = api.injectEndpoints({
    endpoints: (builder) => ({
        refresh: builder.mutation<RefreshResponse, void>({
            query: () => ({
                url: "/refresh",
                method: "POST",
            }),
            invalidatesTags: ["CurrentUser"],
            async onQueryStarted(_credentials, { dispatch, queryFulfilled }) {
                try {
                    const { data: responseBody } = await queryFulfilled;
                    const user = responseBody.data;
                    dispatch(logIn({ username: user.username, email: user.email, userId: user._id, roles: user.roles }));
                } catch(err) {
                    console.error('Refresh mutation failed:', err);
                }
            },
        }),

        login: builder.mutation<AuthResponse, LoginRequest>({
            query: (credentials) => ({
                url: "/login",
                method: "POST",
                body: credentials,
            }),
            invalidatesTags: ["CurrentUser"],
            async onQueryStarted(_credentials, { dispatch, queryFulfilled }) {
                try {
                    const { data : responseBody } = await queryFulfilled;
                    const user = responseBody.data;
                    dispatch(logIn({ username: user.username,
                        email: user.email,
                        userId: user._id,
                        roles: user.roles}));
                } catch (error) {
                    // login failed — no dispatch needed, error surfaces via the mutation's own error state
                    console.error('Login mutation failed:', error);
                }
            },
        }),

        logout: builder.mutation<AuthResponse, void>({
            query: (credentials) => ({
                url: "/logout",
                method: "POST",
                body: credentials,
            }),
            invalidatesTags: ["CurrentUser"],
        }),

        signUp: builder.mutation<AuthResponse, SignUpRequest>({
            query: (credentials) => ({
                url: "/signup",
                method: "POST",
                body: credentials,
            }),
            invalidatesTags: ["CurrentUser", "User"],
            async onQueryStarted(_credentials, { dispatch, queryFulfilled }) {
                try {
                    const { data: responseBody } = await queryFulfilled;
                    const user = responseBody.data;
                    dispatch(logIn({ name: user.name, username: user.username, email: user.email, phoneNumber: user.phoneNumber, userId: user._id, roles: user.roles }));
                } catch(err) {
                    console.error('Signup mutation failed:', err);
                    // signup failed — no dispatch needed, error surfaces via the mutation's own error state
                }
            },
        }),

        createAdmin: builder.mutation<AuthResponse, SignUpRequest>({
            query: (credentials) => ({
                url: "admin/create-admin",
                method: "POST",
                body: credentials,
            }),
            invalidatesTags: ["User"],
        }),

    }),
});

export const {
    useLoginMutation,
    useSignUpMutation,
    useRefreshMutation,
    useLogoutMutation,
    useCreateAdminMutation,
} = authApi;