// Scaffolding generated by Claude
import { api } from "../api";
import type {Role} from "@/dataTypes/user.ts";
import {logIn} from "@/context/authenticationSlice.ts";

export interface SignUpResponse {
    message: string;
    data: AuthUser;
    type: string;
}

export interface SignUpRequest {
    name: string | null,
    username: string | null;
    email: string | null;
    password: string | null;
    phoneNumber: string | null,
    roles: Role[],
}

export interface LoginRequest {
    username?: string;
    email?: string;
    password: string;
}

export interface AuthUser {
    _id: string;
    name: string;
    username: string;
    email: string;
    phoneNumber: string;
    roles: string[];
}

export const authApi = api.injectEndpoints({
    endpoints: (builder) => ({
        login: builder.mutation<AuthUser, LoginRequest>({
            query: (credentials) => ({
                url: "/login",
                method: "POST",
                body: credentials,
            }),
            invalidatesTags: ["CurrentUser"],
            async onQueryStarted(_credentials, { dispatch, queryFulfilled }) {
                try {
                    const { data } = await queryFulfilled;
                    dispatch(logIn({ name: data.name, username: data.username, email: data.email, phoneNumber: data.phoneNumber, userId: data._id, roles: data.roles }));
                } catch {
                    // login failed — no dispatch needed, error surfaces via the mutation's own error state
                }
            },
        }),

        signUp: builder.mutation<SignUpResponse, SignUpRequest>({
            query: (credentials) => ({
                url: "/signup",
                method: "POST",
                body: credentials,
            }),
            invalidatesTags: ["CurrentUser", "User"],
            async onQueryStarted(_credentials, { dispatch, queryFulfilled }) {
                try {
                    const { data: responseBody } = await queryFulfilled;
                    const user = responseBody.data;
                    dispatch(logIn({ name: user.name, username: user.username, email: user.email, phoneNumber: user.phoneNumber, userId: user._id, roles: user.roles }));
                } catch(err) {
                    console.error('Signup mutation failed:', err);
                    // signup failed — no dispatch needed, error surfaces via the mutation's own error state
                }
            },
        }),
    }),
});

export const {
    useLoginMutation,
    useSignUpMutation,
} = authApi;