// Scaffolding generated by Claude
import { api } from "../api.ts";
import type { Room } from "@/dataTypes/room.ts";

export const roomsApi = api.injectEndpoints({
    endpoints: (builder) => ({
        getRooms: builder.query<Room[], void>({
            query: () => ({ url: "/rooms/" }),
            providesTags: ["Room"],
        }),
    }),
});

export const { useGetRoomsQuery } = roomsApi;