//Scaffolding generated by Claude

import { Db, Collection, ObjectId } from "mongodb";

export interface UserDoc {
    _id: ObjectId;
    email: string;
    passwordHash: string;
    createdAt: Date;
}

export type NewUserDoc = Omit<UserDoc, "_id">;

// Pure data access. No hashing, no validation, no HTTP concerns —
// just reads and writes against the "users" collection.
export class UserRepository {
    private readonly users: Collection<UserDoc>;

    constructor(db: Db) {
        this.users = db.collection<UserDoc>("users");
    }

    async findByEmail(email: string): Promise<UserDoc | null> {
        return this.users.findOne({ email });
    }

    async findById(id: string): Promise<UserDoc | null> {
        return this.users.findOne({ _id: new ObjectId(id) });
    }

    async create(user: NewUserDoc): Promise<UserDoc> {
        const result = await this.users.insertOne(user as UserDoc);
        return { ...user, _id: result.insertedId };
    }
}