//Scaffolding generated by Claude.
import assert from "node:assert/strict";
import { ObjectId } from "mongodb";
import { AuthService, InvalidCredentialsError, ValidationError } from "../auth/services/auth.services";
import { UserRepository, UserDoc, NewUserDoc } from "../auth/repository/auth.repository";
import { hashPassword } from "../auth/auth.utils";
import {beforeEach, describe, it } from "node:test";

// A fake repository that satisfies the same interface as UserRepository,
// but stores users in memory instead of hitting MongoDB.
// This lets the test run instantly with no real DB connection.
class FakeUserRepository implements Pick<UserRepository, "findByEmail" | "findById" | "create"> {
    private usersByEmail = new Map<string, UserDoc>();

    async findByEmail(email: string): Promise<UserDoc | null> {
        return this.usersByEmail.get(email) ?? null;
    }

    async findById(id: string): Promise<UserDoc | null> {
        for (const user of this.usersByEmail.values()) {
            if (user._id.toString() === id) return user;
        }
        return null;
    }

    async create(user: NewUserDoc): Promise<UserDoc> {
        const stored: UserDoc = { ...user, _id: new ObjectId() };
        this.usersByEmail.set(user.email, stored);
        return stored;
    }

    // Test-only helper to seed a user directly, bypassing signup logic.
    async seed(email: string, plainPassword: string): Promise<void> {
        const passwordHash = await hashPassword(plainPassword);
        await this.create({ email, passwordHash, createdAt: new Date() });
    }
}

describe("AuthService.login", () => {
    let repository: FakeUserRepository;
    let authService: AuthService;

    const EMAIL = "test@example.com";
    const PASSWORD = "correct-password123";

    beforeEach(async () => {
        repository = new FakeUserRepository();
        authService = new AuthService(repository as unknown as UserRepository);
        await repository.seed(EMAIL, PASSWORD);
    });

    it("returns a token when the email and password are correct", async () => {
        const result = await authService.login(EMAIL, PASSWORD);

        assert.ok(result.token, "expected a token to be returned");
        assert.equal(typeof result.token, "string");
    });

    it("throws InvalidCredentialsError when the password is wrong", async () => {
        await assert.rejects(
            () => authService.login(EMAIL, "wrong-password"),
            InvalidCredentialsError
        );
    });

    it("throws InvalidCredentialsError when the email does not exist", async () => {
        await assert.rejects(
            () => authService.login("nobody@example.com", PASSWORD),
            InvalidCredentialsError
        );
    });

    it("throws ValidationError when email or password is missing", async () => {
        await assert.rejects(
            () => authService.login("", PASSWORD),
            ValidationError
        );
        await assert.rejects(
            () => authService.login(EMAIL, ""),
            ValidationError
        );
    });
});